algoritmo "Escreva Um Algoritimo que leia as dimenções de um retangulo(BASE E ALTURA) e CAUCULE A SUA Area "
// Função :
// Autor :
// Data : 17/07/2022
// Seção de Declarações 
var
     ALTURA,BASE: real

     
inicio

Escreva("Digite o valar do ALTURA do retangulo: ")
leia(ALTURA)
Escreval("Agora Digite a BASE da retangulo")
leia(Base)
Escreval("A area da Seu retanguço é: ", BASE * ALTURA)
// Seção de Comandos 
fimalgoritmo
