// Autor :  Esdras Soares de Oliveira
// Data : 20/04/2022

algoritmo "Procedimento"
procedimento soma
var
aux: inteiro
inicio soma
aux <- N * M
res <- aux
fimprocedimento

var
  res,N,M: inteiro
inicio
escreva("Digite o primeiro nomero: ")
leia(N)
escreva("Digite um segndo numero: ")
leia(M)
soma
escreva("O resultado da sua Multiplicação foi: ",res)
Fimalgoritmo

// Seção de Comandos 
fimalgoritmo
